/**
 * Core message/turn types for the agent harness.
 *
 * Deliberately mirrors the OpenAI chat-completions shape where practical so the
 * RemoteAdapter is a thin passthrough, while staying small enough that the
 * on-device LocalAdapter (RunAnywhere RN SDK) can map without loss.
 */

export type Role = 'system' | 'user' | 'assistant' | 'tool';

export interface ToolCall {
  /** Unique id for pairing with the ToolResult (generated by harness when the model omits one). */
  id: string;
  name: string;
  /** Parsed arguments. Always an object; invalid/unparseable args never reach this type. */
  arguments: Record<string, unknown>;
}

export interface ToolResultMessage {
  role: 'tool';
  toolCallId: string;
  toolName: string;
  /** JSON-serialized result or error payload, already capped to policy limits. */
  content: string;
  isError?: boolean;
}

export interface AssistantMessage {
  role: 'assistant';
  content: string;
  reasoning?: string;
  toolCalls?: ToolCall[];
}

export interface SystemMessage {
  role: 'system';
  content: string;
}

export interface UserMessage {
  role: 'user';
  content: string;
}

export type ChatMessage = SystemMessage | UserMessage | AssistantMessage | ToolResultMessage;

/** JSON Schema subset used for tool parameters (same shape as OpenAI `parameters`). */
export interface JsonSchema {
  type?: string;
  description?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: (string | number | boolean)[];
  [key: string]: unknown;
}

/** Events emitted by an AgentLoop run — the UI renders these directly. */
export type AgentEvent =
  | { type: 'run_started'; runId: string }
  | { type: 'turn_started'; turn: number }
  | { type: 'text_delta'; text: string }
  | { type: 'reasoning_delta'; text: string }
  | {
      /** Parsed result of a model turn: cleaned prose with tool syntax and
       * think blocks removed. UIs render THIS, not the raw stream. */
      type: 'assistant_turn';
      turn: number;
      text: string;
      reasoning: string;
      toolCallCount: number;
    }
  | { type: 'tool_call_proposed'; call: ToolCall }
  | { type: 'approval_required'; call: ToolCall }
  | { type: 'approval_resolved'; call: ToolCall; approved: boolean }
  | { type: 'tool_call_started'; call: ToolCall }
  | { type: 'tool_call_finished'; call: ToolCall; result: string; isError: boolean }
  /** A repeat of an already-executed call was served from cache — nothing ran. UIs should not render it. */
  | { type: 'duplicate_call_suppressed'; call: ToolCall }
  /**
   * The model called a tool that is visible but not runnable this turn
   * (AgentRunConfig.allowExecuteOnly). Distinct from tool_call_finished
   * with isError, because nothing went wrong: the harness declined by
   * design, and a caller counting failures must not count this one.
   */
  | { type: 'tool_call_refused'; call: ToolCall; reason: string }
  | { type: 'parse_retry'; attempt: number; reason: string }
  | { type: 'compaction'; droppedMessages: number }
  | { type: 'turn_finished'; turn: number }
  | {
      type: 'run_finished';
      reason: 'completed' | 'max_turns' | 'cancelled' | 'error' | 'denied';
      finalText: string;
      error?: string;
    };

/** Serializable snapshot written after every step so a killed app can resume. */
export interface RunCheckpoint {
  runId: string;
  turn: number;
  messages: ChatMessage[];
  createdAtMs: number;
}
